/*
This file is generated by a tool, do not edit manually
*/

using System;
using System.Collections.Generic;
using SpeedifyCliWrapper.Common;

namespace SpeedifyCliWrapper.ReturnTypes
{
    public partial class SpeedifyAdapter
    {
		public SpeedifyAdapter DailyDataLimit (SpeedifyAdapter adapter, Nullable<long> dataUsage, int timeout = 60)
		{
			return this._wrapper.Adapter.DailyDataLimit(adapter, dataUsage, timeout);
		}

		public SpeedifyAdapter DailyDataBoost (SpeedifyAdapter adapter, long additionalData, int timeout = 60)
		{
			return this._wrapper.Adapter.DailyDataBoost(adapter, additionalData, timeout);
		}

		public SpeedifyAdapter MonthlyDataLimit (SpeedifyAdapter adapter, Nullable<long> dataUsage, int dayOfReset = 0, int timeout = 60)
		{
			return this._wrapper.Adapter.MonthlyDataLimit(adapter, dataUsage, dayOfReset, timeout);
		}

		public SpeedifyAdapter SetEncryption (SpeedifyAdapter adapter, bool enable, int timeout = 60)
		{
			return this._wrapper.Adapter.SetEncryption(adapter, enable, timeout);
		}

	}
}

